web: python manage.py migrate && python manage.py seed_data && gunicorn playto.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
worker: celery -A playto worker --loglevel=info --concurrency=2
beat: celery -A playto beat --loglevel=info
